# automatically generated by `rake builtins:julia`
module Rugments
  module Lexers
    class Julia
      def self.builtins
        @builtins ||= Set.new %w(exit whos edit load is isa isequal typeof tuple
        ntuple uid hash finalizer convert promote subtype
        typemin typemax realmin realmax sizeof eps promote_type
        method_exists applicable invoke dlopen dlsym system
        error throw assert new Inf Nan pi im)
      end
    end
  end
end
